# Our AIO builder docker file
FROM multiarch/debian-debootstrap:arm64-bullseye

RUN mkdir /repo

RUN apt-get update && apt-get install -yq \
    ca-certificates \
    debootstrap \
    fakeroot \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*